"""Type stubs for xoq Python bindings."""

from __future__ import annotations

# MoQ classes
class MoqConnection:
    def __init__(
        self,
        path: str | None = None,
        token: str | None = None,
        relay: str | None = None,
    ) -> None: ...
    def create_track(self, name: str) -> MoqTrackWriter: ...
    def subscribe_track(self, track_name: str) -> MoqTrackReader | None: ...

class MoqPublisher:
    def __init__(
        self,
        path: str | None = None,
        token: str | None = None,
        relay: str | None = None,
    ) -> None: ...
    def create_track(self, name: str) -> MoqTrackWriter: ...

class MoqSubscriber:
    def __init__(
        self,
        path: str | None = None,
        token: str | None = None,
        relay: str | None = None,
    ) -> None: ...
    def subscribe_track(self, track_name: str) -> MoqTrackReader | None: ...

class MoqTrackWriter:
    def write(self, data: bytes) -> None: ...
    def write_str(self, data: str) -> None: ...

class MoqTrackReader:
    def read(self) -> bytes | None: ...
    def read_string(self) -> str | None: ...

# Iroh classes
class IrohServer:
    def __init__(
        self,
        identity_path: str | None = None,
        alpn: bytes | None = None,
    ) -> None: ...
    def id(self) -> str: ...
    def accept(self) -> IrohConnection | None: ...

class IrohConnection:
    def __init__(
        self,
        server_id: str,
        alpn: bytes | None = None,
    ) -> None: ...
    def remote_id(self) -> str: ...
    def open_stream(self) -> IrohStream: ...
    def accept_stream(self) -> IrohStream: ...

class IrohStream:
    def write(self, data: bytes) -> None: ...
    def write_str(self, data: str) -> None: ...
    def read(self, size: int = 4096) -> bytes | None: ...
    def read_string(self) -> str | None: ...

# Serial classes
class SerialPortInfo:
    name: str
    port_type: str

def list_ports() -> list[SerialPortInfo]: ...

class SerialPort:
    def __init__(self, port: str, baud_rate: int = 115200) -> None: ...
    def write(self, data: bytes) -> int: ...
    def write_str(self, data: str) -> None: ...
    def read(self, size: int = 1024) -> bytes: ...

# Serial bridge classes
class Server:
    def __init__(
        self,
        port: str,
        baud_rate: int = 115200,
        identity_path: str | None = None,
    ) -> None: ...
    def id(self) -> str: ...
    def run(self) -> None: ...
    def run_once(self) -> None: ...

class Client:
    def __init__(self, server_id: str) -> None: ...
    def write(self, data: bytes) -> None: ...
    def write_str(self, data: str) -> None: ...
    def read(self, size: int = 1024) -> bytes | None: ...
    def read_string(self) -> str | None: ...
    def run_interactive(self) -> None: ...

class Serial:
    """pyserial-compatible interface to a remote serial port."""

    in_waiting: int
    is_open: bool
    timeout: float | None
    port: str
    name: str

    def __init__(self, port: str, timeout: float | None = None) -> None: ...
    def write(self, data: bytes) -> int: ...
    def read(self, size: int = 1) -> bytes: ...
    def readline(self) -> bytes: ...
    def reset_input_buffer(self) -> None: ...
    def read_until(self, terminator: bytes | None = None) -> bytes: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Serial: ...
    def __exit__(
        self,
        exc_type: type | None,
        exc_val: BaseException | None,
        exc_tb: object | None,
    ) -> bool: ...
